version: 2.1

jobs:
  test:
    resource_class: small
    docker:
      - image: cimg/python:3.10.8
    environment:
      HOST=localhost
      PORT=27017
      USER=admin
      PASSWORD=admin
    steps:
      - checkout
      - run:
          name: Setup environment
          command: pip install --upgrade pip && pip install -r ./user/requirements.txt
      - run:
          name: Run test
          command: cd user && python manage.py test

workflows:
  test-code:
    jobs:
      - test