db.user.insertOne({
    "display_name": "namprozz",
    "real_name": "Nguyen Van Nam",
    "email": "namnguyenvan@gmai.com",
    "password": "namdeptrai",
    "introduction": "Toi rat dep trai",
    "avatar": "",
    "date_signup": 1586210447,
    "ban_status": false,
    "report": [],
    "comment": [],
    "problem_ac": [],
    "submission": [],
    "contest_join": [],
    "point": 123,
    "blog": [],
    "contest_point": 45,
    "contest_armorial": "silver"
})
db.user.insertOne({
    "display_name": "vietthongminh",
    "real_name": "Ly Thuong Viet",
    "email": "vietthongminh@abc.com",
    "password": "234ssdwfF",
    "introduction": "Toi rat thong minh",
    "avatar": "",
    "date_signup": 1672842376,
    "ban_status": false,
    "report": [],
    "comment": [],
    "problem_ac": [],
    "submission": [],
    "contest_join": [],
    "point": 65,
    "blog": [],
    "contest_point": 100,
    "contest_armorial": "gold"
})
db.user.insertOne({
    "display_name": "toward",
    "real_name": "Toward Linus",
    "email": "towardlinus@linux.com",
    "password": "123dffg8098",
    "introduction": "Hello everyone",
    "avatar": "",
    "date_signup": 1620048894,
    "ban_status": false,
    "report": [],
    "comment": [],
    "problem_ac": [],
    "submission": [],
    "contest_join": [],
    "point": 41,
    "blog": [],
    "contest_point": 10,
    "contest_armorial": "gold"
})
db.user.insertOne({
    "display_name": "ricardo",
    "real_name": "Ricardo Gray",
    "email": "ricardothehow@outlook.com",
    "password": "123456",
    "introduction": "I'm a software developer",
    "avatar": "",
    "date_signup": 1594188304,
    "ban_status": true,
    "report": [],
    "comment": [],
    "problem_ac": [],
    "submission": [],
    "contest_join": [],
    "point": 54,
    "blog": [],
    "contest_point": 12,
    "contest_armorial": ""
})
db.user.insertOne({
    "display_name": "billy",
    "real_name": "Bill Gates",
    "email": "billgates@microsoft.com",
    "password": "534dvvbnBdfgiwe7u8",
    "introduction": "I hate programming",
    "avatar": "",
    "date_signup": 1610183104,
    "ban_status": false,
    "report": [],
    "comment": [],
    "problem_ac": [],
    "submission": [],
    "contest_join": [],
    "point": 1254,
    "blog": [],
    "contest_point": 0,
    "contest_armorial": ""
})
db.user.insertOne({
    "display_name": "hieupc",
    "real_name": "Dang Van Hieu",
    "email": "hieupc@gmail.com",
    "password": "asdfw4etg093458df",
    "introduction": "Hello",
    "avatar": "",
    "date_signup": 1675382706,
    "ban_status": false,
    "report": [],
    "comment": [],
    "problem_ac": [],
    "submission": [],
    "contest_join": [],
    "point": 1,
    "blog": [],
    "contest_point": 27,
    "contest_armorial": "copper"
})
db.user.insertOne({
    "display_name": "nguyentai",
    "real_name": "La Nguyen Tai",
    "email": "taichanh@gmail.com",
    "password": "fasdf21fha",
    "introduction": "I love Dijkstra",
    "avatar": "",
    "date_signup": 1675382706,
    "ban_status": true,
    "report": [],
    "comment": [],
    "problem_ac": [],
    "submission": [],
    "contest_join": [],
    "point": 3456,
    "blog": [],
    "contest_point": 999,
    "contest_armorial": "diamond"
})