db.user.insertOne({
    "displayName": "namprozz",
    "realName": "Nguyen Van Nam",
    "email": "namnguyenvan@gmai.com",
    "password": "namdeptrai",
    "introduction": "Toi rat dep trai",
    "avatar": "",
    "dateSignup": 1586210447,
    "banStatus": false,
    "report": [],
    "comment": [],
    "problemAccepted": [],
    "submission": [],
    "contestJoin": [],
    "point": 123,
    "blog": [],
    "contestPoint": 45,
    "contestArmorial": ["silver"],
    "session": [],
})
db.user.insertOne({
    "displayName": "vietthongminh",
    "realName": "Ly Thuong Viet",
    "email": "vietthongminh@abc.com",
    "password": "234ssdwfF",
    "introduction": "Toi rat thong minh",
    "avatar": "",
    "dateSignup": 1672842376,
    "banStatus": false,
    "report": [],
    "comment": [],
    "problemAccepted": [],
    "submission": [],
    "contestJoin": [],
    "point": 65,
    "blog": [],
    "contestPoint": 100,
    "contestArmorial": ["gold"],
    "session": [],
})
db.user.insertOne({
    "displayName": "toward",
    "realName": "Toward Linus",
    "email": "towardlinus@linux.com",
    "password": "123dffg8098",
    "introduction": "Hello everyone",
    "avatar": "",
    "dateSignup": 1620048894,
    "banStatus": false,
    "report": [],
    "comment": [],
    "problemAccepted": [],
    "submission": [],
    "contestJoin": [],
    "point": 41,
    "blog": [],
    "contestPoint": 10,
    "contestArmorial": ["gold"],
    "session": [],
})
db.user.insertOne({
    "displayName": "ricardo",
    "realName": "Ricardo Gray",
    "email": "ricardothehow@outlook.com",
    "password": "123456",
    "introduction": "I'm a software developer",
    "avatar": "",
    "dateSignup": 1594188304,
    "banStatus": true,
    "report": [],
    "comment": [],
    "problemAccepted": [],
    "submission": [],
    "contestJoin": [],
    "point": 54,
    "blog": [],
    "contestPoint": 12,
    "contestArmorial": [],
    "session": [],
})
db.user.insertOne({
    "displayName": "billy",
    "realName": "Bill Gates",
    "email": "billgates@microsoft.com",
    "password": "534dvvbnBdfgiwe7u8",
    "introduction": "I hate programming",
    "avatar": "",
    "dateSignup": 1610183104,
    "banStatus": false,
    "report": [],
    "comment": [],
    "problemAccepted": [],
    "submission": [],
    "contestJoin": [],
    "point": 1254,
    "blog": [],
    "contestPoint": 0,
    "contestArmorial": [],
    "session": [],
})
db.user.insertOne({
    "displayName": "hieupc",
    "realName": "Dang Van Hieu",
    "email": "hieupc@gmail.com",
    "password": "asdfw4etg093458df",
    "introduction": "Hello",
    "avatar": "",
    "dateSignup": 1675382706,
    "banStatus": false,
    "report": [],
    "comment": [],
    "problemAccepted": [],
    "submission": [],
    "contestJoin": [],
    "point": 1,
    "blog": [],
    "contestPoint": 27,
    "contestArmorial": ["copper"],
    "session": [],
})
db.user.insertOne({
    "displayName": "nguyentai",
    "realName": "La Nguyen Tai",
    "email": "taichanh@gmail.com",
    "password": "fasdf21fha",
    "introduction": "I love Dijkstra",
    "avatar": "",
    "dateSignup": 1675382706,
    "banStatus": true,
    "report": [],
    "comment": [],
    "problemAccepted": [],
    "submission": [],
    "contestJoin": [],
    "point": 3456,
    "blog": [],
    "contestPoint": 999,
    "contestArmorial": ["diamond"],
    "session": [],
})